/-
  EinsteinTest/Dynamic.lean

  Formal core of the evolving-technology extension.  A completion
  frontier maps each observation to the earliest elapsed time at which
  an admissible future technology path can produce it.  The dynamic
  floor is the infimum over strict-refutation witnesses.
-/

import EinsteinTest.Basic

namespace EinsteinTest

variable {W : ObservationalWorld}

/-- A deterministic future technology path. `availableAfter s delay`
    means that an acquisition protocol for observation `s` can be
    initiated after waiting `delay`; `acquisition s delay` is the
    additional execution-and-reduction time from that start. -/
structure DynamicPath (W : ObservationalWorld) where
  availableAfter : W.Obs → ℝ∞ → Prop
  acquisition : W.Obs → ℝ∞ → ℝ∞

/-- Earliest completion time generated by an explicit
    availability--acquisition path. -/
noncomputable def pathCompletion (path : DynamicPath W) (s : W.Obs) : ℝ∞ :=
  ⨅ delay, ⨅ (_ : path.availableAfter s delay),
    delay + path.acquisition s delay

/-- `new` dominates `old` when every old feasible start remains feasible
    and its acquisition time is weakly lower. -/
def DynamicPath.Dominates (new old : DynamicPath W) : Prop :=
  ∀ s delay, old.availableAfter s delay →
    new.availableAfter s delay ∧
      new.acquisition s delay ≤ old.acquisition s delay

/-- Availability--acquisition dominance lowers each completion time. -/
theorem path_completion_mono
    (old new : DynamicPath W) (hDom : new.Dominates old) (s : W.Obs) :
    pathCompletion new s ≤ pathCompletion old s := by
  unfold pathCompletion
  apply le_iInf
  intro delay
  apply le_iInf
  intro hOld
  have hNew := hDom s delay hOld
  have hFirst :
      (⨅ d, ⨅ (_ : new.availableAfter s d),
        d + new.acquisition s d) ≤
      (⨅ (_ : new.availableAfter s delay),
        delay + new.acquisition s delay) :=
    iInf_le _ delay
  have hSecond :
      (⨅ (_ : new.availableAfter s delay),
        delay + new.acquisition s delay) ≤
      delay + new.acquisition s delay :=
    iInf_le _ hNew.1
  exact hFirst.trans (hSecond.trans (add_le_add_right hNew.2 delay))

/-- Dynamic strict-refutation floor for a supplied completion frontier. -/
noncomputable def dynamicTauMin (R : EinsteinReplacement W)
    (completion : W.Obs → ℝ∞) : ℝ∞ :=
  ⨅ s ∈ R.refutationSet, completion s

/-- Any realised strict-refutation witness bounds the dynamic floor. -/
theorem dynamic_floor_of_witness
    (R : EinsteinReplacement W) (completion : W.Obs → ℝ∞)
    {s : W.Obs} (hs : s ∈ R.refutationSet)
    {elapsed : ℝ∞} (hCompletion : completion s ≤ elapsed) :
    dynamicTauMin R completion ≤ elapsed := by
  exact (biInf_le completion hs).trans hCompletion

/-- Pointwise technological improvement on the relevant witness set
    can only lower the dynamic empirical floor. -/
theorem dynamic_tau_mono
    (R : EinsteinReplacement W) (completion completion' : W.Obs → ℝ∞)
    (hDom : ∀ s ∈ R.refutationSet, completion' s ≤ completion s) :
    dynamicTauMin R completion' ≤ dynamicTauMin R completion := by
  unfold dynamicTauMin
  apply le_iInf
  intro s
  apply le_iInf
  intro hs
  exact (biInf_le completion' hs).trans (hDom s hs)

/-- If two completion frontiers agree on every strict-refutation
    witness, their dynamic floors agree. -/
theorem dynamic_tau_congr
    (R : EinsteinReplacement W) (completion completion' : W.Obs → ℝ∞)
    (hEq : ∀ s ∈ R.refutationSet, completion' s = completion s) :
    dynamicTauMin R completion' = dynamicTauMin R completion := by
  apply le_antisymm
  · exact dynamic_tau_mono R completion completion'
      (fun s hs => (hEq s hs).le)
  · exact dynamic_tau_mono R completion' completion
      (fun s hs => (hEq s hs).ge)

/-- Paper Proposition `prop:technology-dominance`: dominance at the
    availability--acquisition layer lowers the induced dynamic floor. -/
theorem dynamic_path_tau_mono
    (R : EinsteinReplacement W) (old new : DynamicPath W)
    (hDom : new.Dominates old) :
    dynamicTauMin R (pathCompletion new) ≤
      dynamicTauMin R (pathCompletion old) := by
  exact dynamic_tau_mono R (pathCompletion old) (pathCompletion new)
    (fun s _ => path_completion_mono old new hDom s)

end EinsteinTest
